backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/assets/images"
public_folder: "assets/images"

collections:
  - name: "projects"
    label: "Projects"
    format: "json"
    folder: "src/content/projects"
    create: true
    publish: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/ProjectLayout.astro" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Cover Image",
          name: "cover",
          widget: "object",
          fields: [
            { label: "Image", name: "image", widget: "image", required: true },
            { label: "Alt Text", name: "alt", widget: "string", required: true }
          ]
        }
      - { 
          label: "Project Images", 
          name: "projectImages", 
          widget: "list", 
          summary: "{{fields.image}} - {{fields.alt}}", 
          fields: [
            { label: "Image", name: "image", widget: "image" },
            { label: "Alt Text", name: "alt", widget: "string" }
          ],
          required: false
        }
      - { label: "Designer", name: "designer", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Reference Docs", "General", "CSS", "Astro"] }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "carousel"
    label: "輪播圖"
    format: "json"
    folder: "src/content/carousel"
    create: true
    publish: true
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "描述", name: "description", widget: "string" }
      - { label: "輪播圖片", name: "image", widget: "image", required: true }
      - { label: "連結", name: "link", widget: "string", required: false }
      - { label: "排序", name: "order", widget: "number", default: 1 }
      - { label: "啟用狀態", name: "active", widget: "boolean", default: true }
      - { label: "草稿", name: "draft", widget: "boolean", default: false }
