backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/assets/images"
public_folder: "/assets/images"

collections:
  - name: "carousel"
    label: "輪播圖"
    format: "json"
    folder: "src/content/carousel"
    create: true
    publish: true
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "描述", name: "description", widget: "string" }
      - { label: "輪播圖片", name: "url", widget: "image", required: true }
      - { label: "連結", name: "link", widget: "string", required: false }
      - { label: "排序", name: "order", widget: "number", default: 1 }
      - { label: "啟用狀態", name: "active", widget: "boolean", default: true }
      - { label: "草稿", name: "draft", widget: "boolean", default: false }

  - name: "projects"
    label: "專案"
    format: "json"
    folder: "src/content/projects"
    create: true
    publish: true
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "描述", name: "description", widget: "string" }
      - { label: "封面圖", name: "cover", widget: "image", required: true }
      - { 
          label: "專案圖片", 
          name: "images", 
          widget: "image",
          required: false,
          allow_multiple: true,
          media_library: {
            config: {
              multiple: true
            }
          }
        }
      - { label: "設計師", name: "designer", widget: "string" }
      - { 
          label: "分類", 
          name: "category", 
          widget: "select", 
          options: ["Residential Design", "Commercial Design", "Office Design"]
        }
      - { label: "草稿", name: "draft", widget: "boolean", default: false }
